protected/controllers/PoinController.php
<?php

class PoinController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column1';

	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}
	public function accessRules()
	{
		return array(
			array('allow', // allow authenticated user to perform 'create', 'update', 'admin', and 'delete' actions
				'actions'=>array('create','update','admin','delete', 'list'),
				'roles'=>array('admin'),
			),
			array('allow', // allow authenticated user to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('@'),
			),			
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
	public function actionIndex()
	{
		$this->actionView();
	}
	
	public function actionView()
	{
		$condition='';
		
		if(isset($_GET['after'])) {
			//belom
			$start = 0; //ambil dari query
		}else{
			$start = 0;
		}
		
		if(isset($_GET['before'])) {
			//belom
		}

		$dataProvider=new CActiveDataProvider('Poin');
		$data = Poin::model()->with('idPeserta', 'idKelompok')->findAll(array('order'=>'timestamp', 'condition'=>$condition));
		$this->render('view', array('data'=>$data, 'dataProvider'=>$dataProvider,'start'=>$start));
	}
	
	/*
	 * Create a new Poin record.
	 */
	 public function actionCreate()
	 {
		$model=new Poin;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Poin']))
		{
			$model->attributes=$_POST['Poin'];
			$model->penerima = 1; /* Lazy to alter database */
			if (($model->id_peserta == 0) || ($model->id_kelompok == 0)){
			  if($model->save())
				$this->redirect(array('view'));
			}
		}
		
		/* Providing lists of Peserta */
		$c = new CDbCriteria;
		$c->order = 'nama_lengkap asc';
		$pesertaProvider = Peserta::model()->findAll($c);
		
		/* Providing lists of Kelompok */
		$c->order = 'nama asc';
		$kelompokProvider = Kelompok::model()->findAll($c);
		
		/* Providing lists of Timestamp */
		$c->order = 'id desc';
		$timestampProvider = Poin::model()->findAll($c);

		$this->render('create',array(
			'model'=>$model,
			'pesertaProvider'=>$pesertaProvider,
			'kelompokProvider'=>$kelompokProvider,
			'timestampProvider'=>$timestampProvider,
		));	    
	 }
	 
	 /**
	 * Lists all models.
	 */
	public function actionList()
	{
		$dataProvider=new CActiveDataProvider('Poin');
		$this->render('list',array(
			'dataProvider'=>$dataProvider,
		));
	}
	
	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'list' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
	        /* Additional note : This is unsafe scheme of deleting entries */
			$this->loadModel($id)->delete();

			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('list'));

	}
	
	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Poin::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}


}

protected/controllers/PostController.php
<?php

class PostController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column1';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'roles'=>array('peserta'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','delete'),
				'roles'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
	public function actions()
    {
        return array(
            'fileUpload'=>'ext.yiiredactor.actions.FileUpload',
            'imageUpload'=>'ext.yiiredactor.actions.ImageUpload',
            'imageList'=>'ext.yiiredactor.actions.ImageList',
        );
    }

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	
	public function actionView($id)
	{
		if (Yii::app()->request->isAjaxRequest) {
			$this->renderPartial('view',array(
				'model'=>$this->loadModel($id),
			));
		} else {	
			$this->render('view',array(
				'model'=>$this->loadModel($id),
			));
		}
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Post;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		} else {
			$model->status = 1;
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		// if(Yii::app()->request->isPostRequest)
		// {
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			//if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('site/index'));
		// }
		// else
		// 	throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Post', array('criteria'=>array('order'=>'id desc','condition'=>'status = 1'),'pagination'=>false));
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Post::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		else if (Yii::app()->user->role == 'peserta') {
			if ($model->status != 1) {
				throw new CHttpException(403,'You don\'t have permission.');
			}
		}
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='post-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/admin/_left.php
<li class="<?php echo $data->kategori ?>">
	<?php 
	$myLink = "
		<h5 class=\"text-title\">
			".$data->judul."
		</h5>
		<label class=\"date\">
			".date('j F Y', strtotime($data->timestamp_published))."
		</label>";
	echo CHtml::link($myLink, array('/post/update','id'=>$data->id))
	?>
</li> 

protected/views/admin/index.php
<?php
/* @var $this SiteController */

$this->pageTitle=Yii::app()->name;
$admin =  Akun::model()->findByPk(Yii::app()->user->id);
?>

<section id="profile-admin" class="row">


<!--<center>
<?php
	//$this->Widget('ext.TimelineJS.SpartaTimeline', array('options' => $timelineData))
?>
       <div id="my-timeline"></div></center>
-->
  <?php $this->widget('TimelineWidget', array('timelineData'=>$timelineData)); ?>

  <div id="poin" class="gadget-2">
  <div class="gadget-container">
    <header class="gadget-header">

      <span>Poin Angkatan</span>
        <!--IF Admin-->
          <a href="<?php echo Yii::app()->createUrl('/poin/list') ?>"><span class="right" data-icon="&#xe00a" aria-hidden="true"></span></a>
          <a href="<?php echo Yii::app()->createUrl('/poin/create') ?>"><span  class="right" data-icon="&#xe004" aria-hidden="true"></span></a>
        <!--END IF-->
    </header>
    <div class="gadget-content">
      <p>
      <?php
        $this->Widget('ext.chartpoin.ChartPoinSparta', array('data'=>$data, 'start'=>$start))
      ?>
    </p>
    </div>
  </div>
</div>
<div class="gadget-2">
    <div class="text-container">
      <header class="gadget-header">
        <span>Articles</span>
        <!--IF Admin-->
          <a href="<?php echo Yii::app()->createUrl('/post/create') ?>"><span class="right" data-icon="&#xe004" aria-hidden="true"></span></a>
        <!--END IF-->
      </header>
      <ul id="sidebar-list">
        <?php $this->widget('bootstrap.widgets.TbListView',array(
          'dataProvider'=>$dataProvider,
          'itemsTagName'=>'ul',
          'template'=>'{items}',
          'itemView'=>'_left',
        )); ?>  
      </ul>
    </div>
</div>
</section>
<!--Scripts dari external source-->
  <script src="<?php echo Yii::app()->baseUrl ?>/js/clock.js"></script>
  <script>
    var currentHours = <?php echo date('H') ?>;
    var currentMinutes = <?php echo date('i') ?>;
    var currentSeconds = <?php echo date('s') ?>;
    function updateClock ( )
    {
      currentSeconds++;
      if (currentSeconds > 59) {
        currentSeconds = 0;
        currentMinutes++;
        if (currentMinutes > 59) {
          currentMinutes = 0;
          currentHours++;
          if (currentHours > 24) {
            // ajax
          }
        }
      }
      // Pad the minutes and seconds with leading zeros, if required
      currentMinutes = ( currentMinutes < 10 ? "0" : "" ) + currentMinutes;
      currentSeconds = ( currentSeconds < 10 ? "0" : "" ) + currentSeconds;

      // Compose the string for display
      var currentTimeString = currentHours + ":" + currentMinutes;
      var currentSecondString = currentSeconds;
      
      // Update the time display
      document.getElementById("hour-minute").firstChild.nodeValue = currentTimeString;
      document.getElementById("second").firstChild.nodeValue = currentSecondString;
    }
    updateClock(); setInterval('updateClock()', 1000 );
  </script>

protected/views/admin/post.php
<div id="text-content"class="content">
	<label><span id="article-category"><?php echo $model->kategori ?></span> / <span id="article-date"><?php echo date('Y/m/d', strtotime($model->timestamp_published)) ?></span></label>
	<a href="<?php echo Yii::app()->createUrl('/post/index') ?>"><h1 id="article-title"><?php echo $model->judul ?></h1></a>

	<div id="article-content">
		<?php echo $model->deskripsi ?>
	</div>
</div>