protected/models/Peserta.php
<?php

/**
 * This is the model class for table "peserta".
 *
 * The followings are the available columns in table 'peserta':
 * @property integer $id
 * @property integer $id_akun
 * @property integer $id_kelompok
 * @property string $nama_lengkap
 * @property string $nama_panggilan
 * @property string $tempat_lahir
 * @property string $tanggal_lahir
 * @property integer $jurusan
 * @property integer $nim_stei
 * @property integer $nim_jurusan
 * @property string $alamat
 * @property string $no_telp
 * @property string $penyakit
 *
 * The followings are the available model relations:
 * @property Inbox[] $inboxes
 * @property Akun $idAkun
 * @property Kelompok $idKelompok
 * @property PesertaTugas[] $pesertaTugases
 * @property Poin[] $poins
 */
class Peserta extends CActiveRecord
{
	public $profpic;
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Peserta the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'peserta';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('id_akun, nama_lengkap, tempat_lahir, tanggal_lahir, nim_stei, alamat_rumah, no_telp, email, alamat', 'required'),
			array('id_akun, id_kelompok, nim_stei, nim_jurusan', 'numerical', 'integerOnly'=>true),
			array('nama_lengkap, jurusan, nama_panggilan, alamat, alamat_latitude, alamat_longitude, alamat_zoom, alamat_rumah', 'length', 'max'=>100),
			array('nim_stei', 'unique', 'className'=>'Peserta'),
			array('email', 'email'),
			array('tempat_lahir', 'length', 'max'=>50),
			array('no_telp', 'length', 'max'=>20),
			array('penyakit', 'safe'),
			array('profpic', 'file', 'allowEmpty' => true, 'types' => 'jpg','safe'=>true, 'maxSize' => 1024 * 800),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, id_akun, id_kelompok, nama_lengkap, nama_panggilan, tempat_lahir, tanggal_lahir, jurusan, nim_stei, nim_jurusan, alamat, no_telp, penyakit', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'inboxes' => array(self::HAS_MANY, 'Inbox', 'id_peserta'),
			'akun' => array(self::BELONGS_TO, 'Akun', 'id_akun'),
			'tambahan' => array(self::HAS_ONE, 'Tambahan', 'id_peserta'),
			'kelompok' => array(self::BELONGS_TO, 'Kelompok', 'id_kelompok'),
			'pesertaTugas' => array(self::HAS_MANY, 'PesertaTugas', 'id_peserta'),
			'poins' => array(self::HAS_MANY, 'Poin', 'id_peserta'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'id_akun' => 'Id Akun',
			'id_kelompok' => 'Id Kelompok',
			'nama_lengkap' => 'Nama Lengkap',
			'nama_panggilan' => 'Nama Panggilan',
			'tempat_lahir' => 'Tempat Lahir',
			'tanggal_lahir' => 'Tanggal Lahir',
			'jurusan' => 'Jurusan',
			'nim_stei' => 'Nim Stei',
			'nim_jurusan' => 'Nim Jurusan',
			'no_telp' => 'Nomor HP',
			'penyakit' => 'Penyakit',
			'alamat' => 'Alamat Bandung',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('id_akun',$this->id_akun);
		$criteria->compare('id_kelompok',$this->id_kelompok);
		$criteria->compare('nama_lengkap',$this->nama_lengkap,true);
		$criteria->compare('nama_panggilan',$this->nama_panggilan,true);
		$criteria->compare('tempat_lahir',$this->tempat_lahir,true);
		$criteria->compare('tanggal_lahir',$this->tanggal_lahir,true);
		$criteria->compare('jurusan',$this->jurusan);
		$criteria->compare('nim_stei',$this->nim_stei);
		$criteria->compare('nim_jurusan',$this->nim_jurusan);
		$criteria->compare('no_telp',$this->no_telp,true);
		$criteria->compare('penyakit',$this->penyakit,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	public function getProfpicImage()
	{
		$path = '/upload/images/profpic/'.$this->nim_stei.'.jpg';
		if (file_exists(getcwd().$path))
			return Yii::app()->baseUrl.$path;
		else 
			return Yii::app()->baseUrl.'/images/default.png';
			//return 'http://www.gravatar.com/avatar/'.md5(strtolower($this->email)).'?s=300&r=G'; 
	}

}

protected/controllers/PesertaController.php
<?php

class PesertaController extends Controller
{
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}
	public function accessRules()
	{
		return array(

			array('allow',
				'actions'=>array('view','list'),
				'users'=>array('*'), //saat udah fix, ubah jadi user all
			),

			array('allow',
				'actions'=>array('index', 'profil'),
				'roles'=>array('peserta'),
			),
			array('allow', 
				'actions'=>array('report'),
				'roles'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
	public function actionIndex() {
		$condition='';
		
		if(isset($_GET['after'])) {
			//belom
			$start = 0; //ambil dari query
		}else{
			$start = 0;
		}
		
		if(isset($_GET['before'])) {
			//belom
		}
		$dataProvider=new CActiveDataProvider('Post', array('criteria'=>array('order'=>'id desc', 'condition'=>'status = 1'),'pagination'=>false));
		$data = Poin::model()->with('idPeserta', 'idKelompok')->findAll(array('order'=>'timestamp', 'condition'=>$condition));
		$timelineData = Timeline::model()->findAll(array('order'=>'timestamp_published'));
		$this->render('index', array('data'=>$data, 'start'=>$start,'dataProvider'=>$dataProvider, 'timelineData'=>$timelineData,));
		}
	public function actionReport() {
		Yii::import('application.extensions.phpexcel.JPhpExcel');
		$c = new CDbCriteria;
		$c->order = 'nama_lengkap asc';
		$model = Peserta::model()->findAll($c);
		$data[1] = array('id','nama_lengkap','tempat_lahir','tanggal_lahir','jurusan','nim_stei','no_telp','email','motivasi','penyakit_pernah','penyakit_sedang','golongan_darah','nomor_kerabat','nomor_ortu','kebersamaan','keaktifan','inisiatif','kesadaran_mahasiswa','kesadaran_bangsa');
		$ctr = 2;
		foreach ($model as $peserta) {
			if ($peserta->tambahan) {
				$data[$ctr] = array(
						$peserta->id,
						$peserta->nama_lengkap,
						$peserta->tempat_lahir,
						$peserta->tanggal_lahir,
						$peserta->jurusan,
						$peserta->nim_stei,
						$peserta->no_telp,
						$peserta->email,
						$peserta->tambahan->motivasi,
						$peserta->tambahan->penyakit_pernah,
						$peserta->tambahan->penyakit_sedang,
						$peserta->tambahan->golongan_darah,
						$peserta->tambahan->nomor_kerabat,
						$peserta->tambahan->nomor_ortu,
						$peserta->tambahan->kebersamaan,
						$peserta->tambahan->keaktifan,
						$peserta->tambahan->inisiatif,
						$peserta->tambahan->kesadaran_mahasiswa, $peserta->tambahan->kesadaran_bangsa,
				);
			}
			$ctr++;
		}
		$xls = new JPhpExcel('UTF-8', false, 'Data Peserta');
		$xls->addArray($data);
		$xls->generateXML('data_sparta');
		exit;
	}
	public function actionList(){
		Yii::import('application.extensions.phpexcel.JPhpExcel');
		$c = new CDbCriteria;
		$c->order = 'nama_lengkap asc';
		$c->addCondition('nim_stei like "16512%"');
		$model = Peserta::model()->findAll($c);
		$this->render('list',array('model'=>$model));	
	}
	public function actionView($id)
	{
			$this->render('view',array('model'=>$this->loadModel($id),));
	}
	public function loadModel($id)
	{
		$model=Peserta::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}
	public function actionProfil()
	{
		$this->layout = '//layouts/column1';

    $model2 = Peserta::model()->findByAttributes(array('id_akun'=>Yii::app()->user->id));
    if ($model2 == null) {
    	throw new CHttpException(404, "Profil tidak lengkap atau tidak ditemukan");
    }
    $model4 = new Location();
   	$model4->latitude = $model2->alamat_latitude;
		$model4->longitude = $model2->alamat_longitude;
		$model4->zoom = $model2->alamat_zoom;
    if(isset($_POST['Peserta']))
    {
      $model2->attributes = $_POST['Peserta'];
      $model4->attributes = $_POST['Location'];
      $model2->setScenario('profil');	
      if ($model2->validate()) {
	      $model2->profpic = CUploadedFile::getInstance($model2, 'profpic');
				$model2->alamat_latitude = $model4->latitude;
				$model2->alamat_longitude = $model4->longitude;
				$model2->alamat_zoom = $model4->zoom;
				if ($model2->save()) {
					if (is_object($model2->profpic)) {
						$path = getcwd().'/upload/images/profpic/'.$model2->nim_stei.'.jpg';
						$model2->profpic->saveAs($path);
						Yii::app()->phpThumb->makeThumb($path, 245, 240);
					}
					Yii::app()->user->setFlash('success', '<strong>Selamat!</strong> Profil berhasil diupdate');
	      	$this->redirect(Yii::app()->user->returnUrl);
				} 
			}
    }
    $this->render('profil',array('model2'=>$model2, 'model4'=>$model4));
	}
	public function actionUpload(){
    $file = CUploadedFile::getInstanceByName('file');
    // Do your business ... save on file system for example,
    // and/or do some db operations for example
    $nim_stei = Akun::model()->findByPk(Yii::app()->user->id)->peserta->nim_stei;
    $file->saveAs('upload/images/profpic/'.$nim_stei.'.jpg');
    // return the new file path
    echo Yii::app()->baseUrl.'/images/'.$file->getName();
	}
}

protected/controllers/PostController.php
<?php

class PostController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column1';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'roles'=>array('peserta'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','delete'),
				'roles'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
	public function actions()
    {
        return array(
            'fileUpload'=>'ext.yiiredactor.actions.FileUpload',
            'imageUpload'=>'ext.yiiredactor.actions.ImageUpload',
            'imageList'=>'ext.yiiredactor.actions.ImageList',
        );
    }

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	
	public function actionView($id)
	{
		if (Yii::app()->request->isAjaxRequest) {
			$this->renderPartial('view',array(
				'model'=>$this->loadModel($id),
			));
		} else {	
			$this->render('view',array(
				'model'=>$this->loadModel($id),
			));
		}
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Post;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		} else {
			$model->status = 1;
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		// if(Yii::app()->request->isPostRequest)
		// {
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			//if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('site/index'));
		// }
		// else
		// 	throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Post', array('criteria'=>array('order'=>'id desc','condition'=>'status = 1'),'pagination'=>false));
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Post::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		else if (Yii::app()->user->role == 'peserta') {
			if ($model->status != 1) {
				throw new CHttpException(403,'You don\'t have permission.');
			}
		}
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='post-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/peserta/_left.php
<li class="<?php echo $data->kategori ?>">
	<?php 
	$myLink = "
		<h5 class=\"text-title\">
			".$data->judul."
		</h5>
		<label class=\"date\">
			".date('j F Y', strtotime($data->timestamp_published))."
		</label>";
	echo CHtml::link($myLink, array('/post/view','id'=>$data->id))
	?>
</li> 

protected/views/peserta/_peserta.php
<h1>Profil Peserta</h1>
<?php echo $form->textFieldRow($model2,'nama_lengkap', array('class'=>'span6')); ?>
<?php echo $form->textFieldRow($model2,'tempat_lahir', array('class'=>'span6','placeholder'=>'Bandung')); ?>
<?php
	 /* Date Management */
	   $date_partitioned = date_format(date_create($model2->tanggal_lahir), 'Y/m/d');
	   
		   $this->widget('zii.widgets.jui.CJuiDatePicker', array(
			'model'=>$model2,
			'attribute'=>'tanggal_lahir',
			'options'=>array(
					'dateFormat'=>'yy-mm-dd',
			), 
			'htmlOptions'=>array(
				'type'=>'date',
                'value'=>$date_partitioned,
            ),
	));
	?>
<?php 
	$arrayJurusan = array(
		'Teknik Informatika'=>'Teknik Informatika',
		'Sistem Teknologi Informasi'=>'Sistem Teknologi Informasi',
	);
?>
<?php echo $form->dropDownListRow($model2,'jurusan', $arrayJurusan, array('class'=>'span6','placeholder'=>'Teknik Informatika')); ?>
<?php echo $form->textFieldRow($model2,'nim_stei', array('class'=>'span6','placeholder'=>'16511007')); ?>
<?php echo $form->textFieldRow($model2,'alamat_rumah', array('class'=>'span6')); ?>
<?php echo $form->textFieldRow($model2,'no_telp', array('class'=>'span6','placeholder'=>'08151231341')); ?>
<?php echo $form->textFieldRow($model2,'email', array('class'=>'span6')); ?>
<?php echo CHtml::image($model2->profpicImage) ?>
<?php echo $form->fileFieldRow($model2,'profpic',array('class'=>'span6')); ?>
<?php echo $form->textFieldRow($model2,'alamat', array('class'=>'span6')); ?>

<?php
	Yii::import('ext.LocationPicker.Location');
	$this->widget ( 'ext.LocationPicker.LocationWidget',
	array (
	  'model' => $model4,
	  'map_key' => 'AIzaSyD6F2jTe35JXiJMs7VyzZJ2sYUMGfEeQ_Q',
	));
?>

<div class="form-actions">
	<button type="submit" class="success button">Simpan</button>
</div>

protected/views/peserta/_tambahan.php
<h1>Tambahan Peserta</h1>

<?php echo $form->textAreaRow($model3,'motivasi', array('class'=>'span6')); ?>
<?php echo $form->textAreaRow($model3,'penyakit_pernah', array('class'=>'span6')); ?>
<?php echo $form->textAreaRow($model3,'penyakit_sedang', array('class'=>'span6')); ?>
<?php echo $form->textFieldRow($model3,'golongan_darah', array('class'=>'span6')); ?>
<?php echo $form->textFieldRow($model3,'nomor_kerabat', array('class'=>'span6')); ?>
<?php echo $form->textFieldRow($model3,'nomor_ortu', array('class'=>'span6')); ?>
<?php echo $form->textAreaRow($model3,'kebersamaan', array('class'=>'span6')); ?>
<?php echo $form->textAreaRow($model3,'keaktifan', array('class'=>'span6')); ?>
<?php echo $form->textAreaRow($model3,'inisiatif', array('class'=>'span6')); ?>
<?php echo $form->textAreaRow($model3,'kesadaran_mahasiswa', array('class'=>'span6')); ?>
<?php echo $form->textAreaRow($model3,'kesadaran_bangsa', array('class'=>'span6')); ?>

<div class="form-actions">
	<a href="#profil" onclick="$('#profil').click()" class="button">Kembali</a>
	<button type="submit" class="success button">Simpan</button>
</div>

protected/views/peserta/index.php
<?php
/* @var $this SiteController */

$this->pageTitle=Yii::app()->name;
$peserta =  Akun::model()->findByPk(Yii::app()->user->id)->peserta;
?>

<section id="profile-peserta" class="row">
  <div id="clock" class="hide-for-small">
    <div class="gadget-container">
      <div class="gadget-content">
        <span data-icon="&#xe002" aria-hidden="true"></span>
        <h1>Today</h1>
        <span id="hour-minute"><?php echo date('H:i') ?></span><span id="second"><?php echo date('s') ?></span>
        <p id="date"><?php echo date('D j F Y') ?></p>
      </div>
    </div>
  </div>
  <div class="profile">
    <div class="profile-container gadget-container">
    
        <div class="profile-pic" style="background:url(<?php echo ($peserta->profpicImage); ?>) no-repeat;"></div>
        <div class="profile-desc">
          <h1 class="nama"><?php echo $peserta->nama_lengkap ?></h1>
          <h3 class="nim"><?php echo $peserta->nim_stei ?></h3>
          <p class="jurusan"><?php echo $peserta->jurusan ?></p>
          <a href="<?php echo Yii::app()->createUrl('/peserta/profil') ?>"><span class="transparent bottom-corner" data-icon="&#xe000" aria-hidden="true"></span></a>
        </div>

    </div>
  </div>
  
  <div id="map">
    <div id="map-container"class="gadget-container clear">
      <div id="map-area"></div>
    </div>
  </div>  

  <?php $this->widget('TimelineWidget', array('timelineData'=>$timelineData)); ?>

<div id="poin" class="gadget-2">
  <div class="gadget-container">
    <header class="gadget-header">
      <span>Poin Angkatan</span>
    </header>
    <div class="gadget-content">
      <p>
      <?php
        $this->Widget('ext.chartpoin.ChartPoinSparta', array('data'=>$data, 'start'=>$start))
      ?>
    </p>
    </div>
  </div>
</div>
<div class="gadget-2">
    <div class="text-container">
      <header class="gadget-header">
        <span>Articles</span>
      </header>
      <ul id="sidebar-list">
        <?php $this->widget('bootstrap.widgets.TbListView',array(
          'dataProvider'=>$dataProvider,
          'itemsTagName'=>'ul',
          'template'=>'{items}',
          'itemView'=>'_left',
        )); ?>  
      </ul>
    </div>
</div>

</section>
<!--Scripts dari external source-->
  <script src="<?php echo Yii::app()->baseUrl ?>/js/clock.js"></script>
  <script>
    var maplace = new Maplace({
      map_div: '#map-area'
      ,locations: [
        {
          lat: <?php echo $peserta->alamat_latitude ?>, 
          lon: <?php echo $peserta->alamat_longitude ?>,
          zoom: 16
        }]
      ,styles: {
        'Other style': 
        [
          {
            stylers: [
              { hue: "#00ffe6" },
              { saturation: -20 }]
          }, 
          {
            featureType: "road",
            elementType: "geometry",
            stylers: 
              [
                { lightness: 100 },
                { visibility: "simplified" }
              ]
          }, 
          {
          featureType: "road",
          elementType: "labels",
          stylers: 
            [
              { visibility: "off" }
            ]
          }],
        'Night': 
        [
          {
            featureType: 'all',
            stylers: 
            [
              { invert_lightness: 'true' }
            ]
          }],
        'Greyscale': 
        [
          {              
            featureType: 'all',
            stylers: 
            [
              { saturation: -100 },
              { gamma: 0.50 }
            ]
          }]}
      ,controls_on_map: false
    }); 
    maplace.Load(); 
    var currentHours = <?php echo date('H') ?>;
    var currentMinutes = <?php echo date('i') ?>;
    var currentSeconds = <?php echo date('s') ?>;
    function updateClock ( )
    {
      currentSeconds++;
      if (currentSeconds > 59) {
        currentSeconds = 0;
        currentMinutes++;
        if (currentMinutes > 59) {
          currentMinutes = 0;
          currentHours++;
          if (currentHours > 24) {
            // ajax
          }
        }
      }
      // Pad the minutes and seconds with leading zeros, if required
      currentMinutes = ( currentMinutes.length < 2 ? "0" : "" ) + currentMinutes;
      currentSeconds = ( currentSeconds < 10 ? "0" : "" ) + currentSeconds;

      // Compose the string for display
      var currentTimeString = currentHours + ":" + currentMinutes;
      var currentSecondString = currentSeconds;
      
      // Update the time display
      document.getElementById("hour-minute").firstChild.nodeValue = currentTimeString;
      document.getElementById("second").firstChild.nodeValue = currentSecondString;
    }
    updateClock(); setInterval('updateClock()', 1000 );
  </script>

  
<!--Scripts END-->

protected/views/peserta/list.php
<div id="profile-peserta" class="row">
	<div id="list-peserta" class="large-10 columns small-centered">
		<div class="row">
			<input type="search" class="search center small-8 columns small-centered" placeholder="Search by Name or NIM"\>
			<div class="small-11 small-centered columns">
			<span class="sort small-6 large-3 columns butt" data-sort="nama">Sort by Name</span>
    		<span class="sort small-6 large-3 columns butt" data-sort="nim">Sort by NIM</span>
    		<!--<span class="sort small-4 large-2 columns butt" id="filter-IF">Show IF</span>
    		<span class="sort small-4 large-2 columns butt" id="filter-STI">Show STI</span>
    		<span class="sort small-4 large-2 columns butt" id="filter-none">Show All</span>
    		-->
    		</div>
		</div>
		
		<ul class="row list no-bullet">
		<?php foreach ($model as $peserta): ?>
		<a href="<?php echo Yii::app()->createUrl('/peserta/view', array('id'=>$peserta->id)) ?>">
		  <li class="profile list">
		    <div class="profile-container gadget-container">
		        <div class="profile-pic" style="background:url(<?php echo ($peserta->profpicImage); ?>) no-repeat;"></div>
		        <div class="profile-desc">
		          <h4 class="nama"><?php echo $peserta->nama_lengkap ?></h4>
		          <h5 class="nim"><?php echo $peserta->nim_stei ?></h5>
		          <p class="jurusan"><?php echo $peserta->jurusan ?></p>
		        </div>

		    </div>
		  </li> 
		</a>
		<?php endforeach ?>
		
		</ul>
		<footer>
		<p id="copyright">Total: <?php echo count($model)?></p>
		</footer>
	</div>
</div>
<script>
	var options = {
    valueNames: [ 'nama', 'nim', 'jurusan' ]
};

var pesertaList = new List('list-peserta', options);

    $('#filter-IF').click(function() {
        featureList.filter(function(item) {
            if (item.values().jurusan == "Teknik Informatika") {
                return true;
            } else {
                return false;
            }
        });
        return false;
    });

    $('#filter-STI').click(function() {
        featureList.filter(function(item) {
            if (item.values().jurusan == "Sistem Teknologi Informasi") {
                return true;
            } else {
                return false;
            }
        });
        return false;
    });
    $('#filter-none').click(function() {
        featureList.filter();
        return false;
    });
</script>

protected/views/peserta/profil.php
<div class="gadget-center">
  <div class="gadget-container">

 <div class="gadget-content">
<div class="row" id="sparta-register">
 <?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
    'id'=>'register-form',
    'enableClientValidation'=>true,
    'clientOptions'=>array(
        'validateOnSubmit'=>true,
    ),
    'htmlOptions' => array('enctype' => 'multipart/form-data'),
)); ?>
<div class="row">
 <?php // echo $form->errorSummary($model); ?>
 <?php // echo $form->errorSummary($model2); ?>
 <?php // echo $form->errorSummary($model3); ?>

  <?php $this->renderPartial('_peserta', array('form'=>$form, 'model2'=>$model2,'model4'=>$model4)); ?>

</div>
<?php $this->endWidget(); ?>
  <script>
  $(function () {
    $("#registrasi").fitText(0.5, { minFontSize: '65px', maxFontSize: '180px' });
  });
  $(document).ready( function() {
    $('.gllpSearchButton').click();
  });
  </script>
</div><!-- page -->
    
    </div>
  </div>
</div>